version: '3.8'

services:
  elasticsearch:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC
    volumes:
      - ./.qdrant/storage:/qdrant/storage